define({
  more_title: 'المزيد',
  more_profile: 'ملفي الشخصي',
  more_settings: 'الإعدادات',
  more_notifications: 'الإشعارات',
  more_analytics: 'تحليلات الإنفاق',
  more_locate: 'ابحث عن صراف أو فرع',
  more_contact: 'تواصل مع الدعم',
  more_language: 'اللغة',
  more_sign_out: 'تسجيل الخروج',
  more_security: 'الأمان والخصوصية',
  more_limits: 'حدود المعاملات',
  more_feedback: 'التغذية الراجعة',
  more_section_account: 'الحساب',
  more_section_profile: 'الملف الشخصي والإعدادات',
  more_section_services: 'الخدمات',
  more_section_apps: 'الطلبات',
  more_section_support: 'الدعم',
  more_primary_acct: 'الحساب الأساسي',
  more_open_acct: 'فتح حساب جديد',
  more_profile_kyc: 'الملف الشخصي والتوثيق',
  more_theme: 'المظهر والتخصيص',
  more_track_app: 'تتبع الطلب',
  more_live_chat: 'المحادثة المباشرة',
  more_call_center: 'مركز الاتصال',
  more_investments: 'الاستثمارات',
  more_forex: 'العملات الأجنبية',
  more_statements: 'كشوف الحساب',
  more_signout_confirm: 'تسجيل الخروج؟',
  more_signout_sub: 'ستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى حسابك.',
  more_rm_label: 'مدير علاقتك',
  more_stat_accounts: 'الحسابات',
  more_stat_cards: 'البطاقات',
  more_stat_verified: 'موثق',
  more_notif_unread: 'غير مقروء',
  more_notif_caught_up: 'أنت مواكب للأخبار',
  more_notif_empty: 'لا توجد إشعارات غير مقروءة الآن.',
  more_notif_channels: 'قنوات الإشعارات',
  more_push_notif: 'إشعارات الدفع',
  more_push_sub: 'تنبيهات داخل التطبيق',
  more_email_notif: 'إشعارات البريد الإلكتروني',
  more_alert_cats: 'فئات التنبيهات',
  more_alert_security: 'تنبيهات الأمان',
  more_alert_tx: 'تنبيهات المعاملات',
  more_alert_reminders: 'تذكيرات الدفع',
  more_alert_offers: 'العروض والترقيات',
  more_sec_auth: 'الوصول والمصادقة',
  more_sec_face_id: 'Face ID / البيومتري',
  more_sec_face_sub: 'تسجيل الدخول بالبصمة أو الوجه',
  more_sec_mpin_lock: 'قفل MPIN',
  more_sec_mpin_sub: 'يلزم رمز PIN من 6 أرقام عند التشغيل',
  more_sec_2fa: 'المصادقة الثنائية (OTP)',
  more_sec_2fa_sub: 'OTP عبر الرسائل للمعاملات',
  more_sec_creds: 'بيانات الاعتماد',
  more_sec_change_mpin: 'تغيير MPIN',
  more_sec_mpin_row_sub: 'تحديث رمز PIN من 6 أرقام',
  more_sec_change_pwd: 'تغيير كلمة المرور',
  more_sec_pwd_row_sub: 'تحديث كلمة مرور تسجيل الدخول',
  more_sec_sessions: 'الجلسات النشطة',
  more_sec_end_all: 'إنهاء الكل',
  more_sec_end: 'إنهاء',
  more_sec_trusted: 'الأجهزة الموثوقة',
  more_sec_remove: 'إزالة',
  more_sec_no_trusted: 'لا توجد أجهزة موثوقة',
  more_this_device: 'هذا الجهاز',
  more_sec_update_mpin: 'تحديث MPIN',
  more_sec_mpin_hint: 'أدخل رمز PIN من 6 أرقام',
  more_sec_cur_mpin: 'MPIN الحالي',
  more_sec_new_mpin: 'MPIN الجديد',
  more_sec_confirm_mpin: 'تأكيد MPIN الجديد',
  more_sec_update_pwd: 'تحديث كلمة المرور',
  more_sec_pwd_hint: '8 أحرف على الأقل · حرف كبير · رقم · رمز',
  more_sec_cur_pwd: 'كلمة المرور الحالية',
  more_sec_new_pwd: 'كلمة المرور الجديدة',
  more_sec_confirm_pwd: 'تأكيد كلمة المرور الجديدة',
  more_kyc_verified: 'KYC موثق',
  more_personal_info: 'المعلومات الشخصية',
  more_kyc_locked: 'مقفول بـ KYC',
  more_contact_details: 'تفاصيل التواصل',
  more_mobile: 'الجوال',
  more_email_lbl: 'البريد الإلكتروني',
  more_address: 'العنوان',
  more_edit_contact: 'تعديل تفاصيل التواصل',
  more_save_changes: 'حفظ التغييرات',
  more_stmt_select_acct: 'اختر الحساب',
  more_stmt_period: 'فترة الكشف',
  more_stmt_preparing: 'جارٍ التحضير…',
  more_theme_preview: 'معاينة',
  more_theme_appearance: 'المظهر',
  more_theme_accent: 'لون التمييز',
  more_theme_text_size: 'حجم النص',
  more_theme_light: 'فاتح',
  more_theme_dark: 'داكن',
  more_theme_system: 'النظام',
  more_theme_normal: 'عادي',
  more_theme_large: 'كبير',
  more_theme_selected: ':المحدد',
  more_theme_apply: 'تطبيق التغييرات',
  more_inv_total: 'إجمالي قيمة المحفظة',
  more_inv_return: 'العائد السنوي',
  more_inv_active_funds: 'صناديق نشطة',
  more_inv_alloc: 'توزيع الأصول',
  more_inv_funds: 'صناديقي',
  more_inv_more: 'استثمر المزيد',
  more_inv_withdraw: 'سحب',
  more_forex_title: 'العملات الأجنبية والأسعار',
  more_forex_live: 'أسعار مباشرة',
  more_forex_currency: 'العملة',
  more_forex_buy: 'شراء',
  more_forex_sell: 'بيع',
  more_track_contact: 'التواصل مع الموظف المعين',
  more_primary_desc: 'يُستخدم حسابك الأساسي لخصم الرواتب والتحويلات الافتراضية.',
  more_set_primary: 'تعيين كحساب أساسي',
  more_already_primary: 'حساب أساسي بالفعل',
  acc_dl_statement: 'تنزيل كشف الحساب',
  acc_filter_all: 'الكل',
  acc_format: 'الصيغة',
  acc_sms_alerts: 'تنبيهات SMS',
  btn_cancel: 'إلغاء',
  home_qa_loans: 'القروض',
  notif_mark_all_read: 'تحديد الكل كمقروء',
});
