define({
  cards_title: 'بطاقاتي',
  cards_add: 'إضافة بطاقة',
  cards_tab_debit: 'بطاقة خصم',
  cards_tab_credit: 'بطاقة ائتمان',
  cards_tab_virtual: 'بطاقة افتراضية',
  cards_spend_limit: 'حد الإنفاق',
  cards_block: 'إيقاف البطاقة',
  cards_set_limit: 'تحديد الحد',
  cards_change_pin: 'تغيير الرقم السري',
  cards_view_details: 'عرض التفاصيل',
  cards_hotlist: 'القائمة السوداء',
  cards_manage: 'إدارة',
  cards_reissue: 'إعادة إصدار',
  cards_freeze: 'تجميد',
  cards_unfreeze: 'رفع التجميد',
  cards_month_spend: 'الإنفاق الشهري',
  cards_available: 'المتاح',
  cards_credit_limit: 'حد الائتمان',
  cards_expires: 'تنتهي',
  cards_subtitle: 'انقر على بطاقة لعرض التفاصيل',
  cards_new_card: 'بطاقة جديدة',
  cards_set_limits: 'تحديد الحدود',
  cards_spending_limits: 'حدود الإنفاق',
  cards_disputes: 'النزاعات',
  cards_e_statement: 'كشف إلكتروني',
  cards_info: 'معلومات البطاقة',
  cards_replace: 'استبدال البطاقة',
  cards_daily: 'يومي',
  cards_monthly: 'شهري',
  cards_daily_limit: 'الحد اليومي',
  cards_monthly_limit: 'الحد الشهري',
  cards_save_limits: 'حفظ الحدود',
  cards_no_tx: 'لا توجد معاملات بعد',
  cards_auth_title: 'تحقق من هويتك',
  cards_auth_sub: 'اختر طريقة للمصادقة لعرض تفاصيل البطاقة',
  cards_auth_bio: 'بيومتري',
  cards_auth_bio_sub: 'استخدم Face ID أو بصمة الإصبع',
  cards_auth_mpin_sub: 'أدخل رمز MPIN المكون من 6 أرقام',
  cards_auth_mpin_hint: 'أدخل رمز الجوال المكون من 6 أرقام',
  cards_auth_otp: 'OTP عبر الرسائل',
  cards_view_front: 'عرض الواجهة',
  cards_view_back: 'عرض الخلف',
  cards_block_reason: 'حدد سبب حجب هذه البطاقة. يمكن التراجع عن هذا الإجراء.',
  cards_confirm_block: 'حجب البطاقة',
  cards_request: 'طلب بطاقة جديدة',
  cards_debit_card: 'بطاقة خصم',
  cards_debit_sub: 'مرتبطة بحسابك الجاري',
  cards_credit_card: 'بطاقة ائتمان',
  cards_credit_sub: 'يخضع لموافقة الائتمان',
  cards_virtual_card: 'بطاقة افتراضية',
  cards_virtual_sub: 'فورية، للمشتريات عبر الإنترنت',
  home_recent_tx: 'آخر المعاملات',
  home_see_all: 'عرض الكل',
  lbl_active: 'نشط',
  login_mpin: 'MPIN',
  login_mpin_label: 'أدخل رمز MPIN',
  btn_cancel: 'إلغاء',
});
