define({
  root: {
    cards_title: 'My Cards',
    cards_add: 'Add Card',
    cards_tab_debit: 'Debit',
    cards_tab_credit: 'Credit',
    cards_tab_virtual: 'Virtual',
    cards_spend_limit: 'Spend Limit',
    cards_block: 'Block Card',
    cards_set_limit: 'Set Limit',
    cards_change_pin: 'Change PIN',
    cards_view_details: 'View Details',
    cards_hotlist: 'Hotlist',
    cards_manage: 'Manage',
    cards_reissue: 'Reissue',
    cards_freeze: 'Freeze',
    cards_unfreeze: 'Unfreeze',
    cards_month_spend: 'Month Spend',
    cards_available: 'Available',
    cards_credit_limit: 'Credit Limit',
    cards_expires: 'Expires',
    cards_subtitle: 'Tap a card to view details',
    cards_new_card: 'New Card',
    cards_set_limits: 'Set Limits',
    cards_spending_limits: 'Spending Limits',
    cards_disputes: 'Disputes',
    cards_e_statement: 'e-Statement',
    cards_info: 'Card Info',
    cards_replace: 'Replace Card',
    cards_daily: 'Daily',
    cards_monthly: 'Monthly',
    cards_daily_limit: 'Daily Limit',
    cards_monthly_limit: 'Monthly Limit',
    cards_save_limits: 'Save Limits',
    cards_no_tx: 'No transactions yet',
    cards_auth_title: 'Verify Your Identity',
    cards_auth_sub: 'Choose how to authenticate to view card details',
    cards_auth_bio: 'Biometric',
    cards_auth_bio_sub: 'Use Face ID or Fingerprint',
    cards_auth_mpin_sub: 'Enter your 6-digit MPIN',
    cards_auth_mpin_hint: 'Enter your 6-digit Mobile PIN',
    cards_auth_otp: 'OTP via SMS',
    cards_view_front: 'View Front',
    cards_view_back: 'View Back',
    cards_block_reason: 'Select a reason for blocking this card. This action can be reversed.',
    cards_confirm_block: 'Block Card',
    cards_request: 'Request New Card',
    cards_debit_card: 'Debit Card',
    cards_debit_sub: 'Linked to your current account',
    cards_credit_card: 'Credit Card',
    cards_credit_sub: 'Subject to credit approval',
    cards_virtual_card: 'Virtual Card',
    cards_virtual_sub: 'Instant, for online purchases',
    home_recent_tx: 'Recent Transactions',
    home_see_all: 'See All',
    lbl_active: 'Active',
    login_mpin: 'MPIN',
    login_mpin_label: 'Enter MPIN',
    btn_cancel: 'Cancel',
  },
  ar: true
});
