define({
  conf_success_title:    'تمّت عملية التحويل!',
  conf_success_sub:      'أموالك في طريقها',
  conf_failure_title:    'فشل التحويل',
  conf_failure_sub:      'حدث خطأ ما. يرجى المحاولة مجدداً.',
  conf_pending_title:    'في انتظار الموافقة',
  conf_pending_sub:      'تحويلك بانتظار الاعتماد',
  conf_rejected_title:   'تم رفض التحويل',
  conf_rejected_sub:     'لم تتم الموافقة على هذا التحويل',
  conf_lbl_success:      'مكتمل',
  conf_lbl_failure:      'فشل',
  conf_lbl_pending:      'قيد الانتظار',
  conf_lbl_rejected:     'مرفوض',
  conf_amount_sent:      'المبلغ المُحوَّل',
  conf_ref_no:           'رقم المرجع',
  conf_date_time:        'التاريخ والوق��',
  conf_status:           'الحالة',
  conf_receipt_title:    'الإيصال',
  conf_download_receipt: 'تنزيل الإيصال',
  conf_generating:       'جارٍ الإنشاء…',
  conf_generating_toast: 'جارٍ إنشاء ملف PDF…',
  conf_download_success: 'تم تنزيل الإيصال',
  conf_download_error:   'تعذّر إنشاء الإيصال. يرجى المحاولة مجدداً.',
  conf_back_payments:    'العودة إلى المدفوعات'
});
