define({
  pay_title: 'المدفوعات',
  pay_transfer: 'تحويل',
  pay_more_payments: 'مدفوعات أخرى',
  pay_own_account: 'حساباتي',
  pay_within_bank: 'داخل البنك',
  pay_domestic: 'محلي',
  pay_international: 'دولي',
  pay_gcc_rtgs: 'GCC RTGS',
  pay_afaq: 'آفاق',
  pay_qr: 'دفع QR',
  pay_adhoc: 'تحويل مباشر',
  pay_beneficiaries: 'المستفيدون',
  pay_templates: 'القوالب',
  pay_scheduled: 'المدفوعات المجدولة',
  pay_standing: 'التعليمات الدائمة',
  pay_bulk: 'المدفوعات الجماعية',
  pay_bills: 'دفع الفواتير',
  pay_step_recipient: 'المستفيد',
  pay_step_amount: 'المبلغ',
  pay_step_review: 'المراجعة',
  pay_step_verify: 'التحقق',
  pay_select_recipient: 'اختر المستفيد',
  pay_enter_amount: 'أدخل المبلغ',
  pay_review_transfer: 'مراجعة التحويل',
  pay_transfer_type: 'نوع التحويل',
  pay_other_banks: 'بنوك أخرى',
  pay_swift: 'دولي',
  pay_purpose: 'الغرض',
  pay_note: 'ملاحظة (اختياري)',
  pay_schedule: 'جدولة',
  pay_schedule_date: 'تاريخ التحويل',
  pay_amount_placeholder: '0.00',
  pay_quick_amounts: 'مبالغ سريعة',
  pay_from_account: 'من حساب',
  pay_to_beneficiary: 'إلى',
  pay_transfer_amount: 'المبلغ',
  pay_btn_continue: 'متابعة',
  pay_btn_confirm: 'تأكيد وإرسال OTP',
  pay_btn_verify: 'تحقق وحوّل',
  pay_btn_resend: 'إعادة إرسال OTP',
  pay_otp_title: 'أدخل رمز OTP',
  pay_otp_subtitle: 'تم إرسال رمز لمرة واحدة إلى جوالك المسجل',
  pay_success_title: 'تم التحويل بنجاح!',
  pay_success_ref: 'رقم المرجع',
  pay_success_amount: 'المبلغ المحوّل',
  pay_success_date: 'التاريخ والوقت',
  pay_success_btn_home: 'العودة إلى الرئيسية',
  pay_success_btn_share: 'مشاركة الإيصال',
  pay_err_invalid_amount: 'أدخل مبلغاً صحيحاً',
  pay_err_select_ben: 'يرجى اختيار مستفيد',
  pay_err_failed: 'فشل التحويل. يرجى المحاولة مجدداً.',
  pay_err_otp_invalid: 'رمز OTP غير صحيح. حاول مجدداً.',
  pay_err_otp_failed: 'فشل التحقق من OTP.',
  pay_countdown: 'إعادة الإرسال خلال {time}',
  pay_fund_transfer: 'تحويل الأموال',
  pay_tracker: 'متابعة المدفوعات',
  pay_share_qr: 'مشاركة QR',
  pay_scan_pay: 'مسح والدفع',
  pay_add_ben: '+ إضافة',
  pay_new_scheduled: '+ جدولة دفعة جديدة',
  pay_recent_ben: 'المستفيدون الأخيرون',
  pay_no_ben: 'لا يوجد مستفيدون بعد',
  pay_transfer_to: 'إرسال إلى',
  pay_you_sending: 'أنت ترسل',
  pay_service_charges: 'رسوم الخدمة',
  pay_total_debit: 'إجمالي الخصم',
  pay_btn_review: '← مراجعة التحويل',
  pay_sending: 'جارٍ الإرسال…',
  pay_verify_title: 'تحقق من التحويل',
  pay_otp_sent: 'تم إرسال رمز مكون من 6 أرقام إلى',
  pay_resend_in: 'إعادة الإرسال خلال',
  pay_money_way: 'أموالك في طريقها',
  pay_amount_sent: 'المبلغ المرسل',
  pay_completed: 'مكتمل',
  pay_btn_receipt: 'الإيصال',
  pay_btn_track: 'تتبع',
  pay_back_payments: 'العودة إلى المدفوعات',
  pay_schedule_later: 'جدولة لاحقاً',
  pay_account_no: 'رقم الحساب.',
  pay_within_bank_sub: 'تحويلات داخل البنك',
  pay_other_banks_sub: 'تحويل محلي',
  pay_intl: 'دولي',
  pay_intl_sub: 'سويفت / آيبان',
  lbl_from: 'من',
  lbl_to: 'إلى',
  lbl_status: 'الحالة',
});
