define({
  root: {
    appName: 'OBDX Bank',
    nav_home: 'Home',
    nav_accounts: 'Accounts',
    nav_pay: 'Pay',
    nav_cards: 'Cards',
    nav_more: 'More',
    interrupt_otp_title: 'One-Time Password',
    interrupt_otp_subtitle: 'Enter the OTP sent to your registered mobile number',
    interrupt_otp_btn: 'Verify OTP',
    interrupt_otp_resend: 'Resend OTP',
    interrupt_approval_title: 'Approval Required',
    interrupt_approval_sub: 'This transaction requires approval from an authoriser',
    interrupt_approval_btn: 'Submit for Approval',
    interrupt_cancel: 'Cancel',
    interrupt_countdown: 'OTP expires in {time}',
    btn_cancel: 'Cancel',
    btn_close: 'Close',
    btn_save: 'Save',
    btn_confirm: 'Confirm',
    btn_retry: 'Retry',
    btn_back: 'Back',
    btn_done: 'Done',
    btn_next: 'Next',
    btn_submit: 'Submit',
    btn_download: 'Download',
    btn_load_more: 'Load More',
    btn_share: 'Share',
    btn_confirm_block: 'Confirm Block',
    btn_submit_req: 'Submit Request',
    btn_subscribe: 'Subscribe',
    lbl_from: 'From',
    lbl_to: 'To',
    lbl_amount: 'Amount',
    lbl_date: 'Date',
    lbl_status: 'Status',
    lbl_ref: 'Reference No.',
    lbl_active: 'Active',
    lbl_inactive: 'Inactive',
    lbl_today: 'Today',
    lbl_yesterday: 'Yesterday',
    lbl_credit: 'Credit',
    lbl_debit: 'Debit',
    lbl_bill: 'Bill',
    status_success: 'Success',
    status_pending: 'Pending',
    status_failed: 'Failed',
    err_generic: 'Something went wrong. Please try again.',
    err_no_network: 'No network connection. Please check your internet.',
    currency_lyd: 'LYD',
    currency_aed: 'AED',
    currency_usd: 'USD',
  },
  ar: true
});
