define({
  appName: 'OBDX Bank',
  nav_home: 'الرئيسية',
  nav_accounts: 'الحسابات',
  nav_pay: 'الدفع',
  nav_cards: 'البطاقات',
  nav_more: 'المزيد',
  interrupt_otp_title: 'كلمة المرور لمرة واحدة',
  interrupt_otp_subtitle: 'أدخل رمز OTP المرسل إلى جوالك المسجل',
  interrupt_otp_btn: 'تحقق من OTP',
  interrupt_otp_resend: 'إعادة إرسال OTP',
  interrupt_approval_title: 'تتطلب موافقة',
  interrupt_approval_sub: 'تتطلب هذه المعاملة موافقة من مُفوِّض',
  interrupt_approval_btn: 'إرسال للموافقة',
  interrupt_cancel: 'إلغاء',
  interrupt_countdown: 'ينتهي OTP خلال {time}',
  btn_cancel: 'إلغاء',
  btn_close: 'إغلاق',
  btn_save: 'حفظ',
  btn_confirm: 'تأكيد',
  btn_retry: 'إعادة المحاولة',
  btn_back: 'رجوع',
  btn_done: 'تم',
  btn_next: 'التالي',
  btn_submit: 'إرسال',
  btn_download: 'تنزيل',
  btn_load_more: 'تحميل المزيد',
  btn_share: 'مشاركة',
  btn_confirm_block: 'تأكيد الحجب',
  btn_submit_req: 'إرسال الطلب',
  btn_subscribe: 'اشتراك',
  lbl_from: 'من',
  lbl_to: 'إلى',
  lbl_amount: 'المبلغ',
  lbl_date: 'التاريخ',
  lbl_status: 'الحالة',
  lbl_ref: 'رقم المرجع',
  lbl_active: 'نشط',
  lbl_inactive: 'غير نشط',
  lbl_today: 'اليوم',
  lbl_yesterday: 'أمس',
  lbl_credit: 'دائن',
  lbl_debit: 'مدين',
  lbl_bill: 'فاتورة',
  status_success: 'ناجح',
  status_pending: 'قيد الانتظار',
  status_failed: 'فشل',
  err_generic: 'حدث خطأ ما. يرجى المحاولة مجدداً.',
  err_no_network: 'لا يوجد اتصال بالإنترنت.',
  currency_lyd: 'د.ل',
  currency_aed: 'درهم',
  currency_usd: 'دولار',
});
