define({
  appName: 'بنك أمان',

  // ── Navigation ────────────────────────────────────────────────
  nav_home:     'الرئيسية',
  nav_accounts: 'الحسابات',
  nav_pay:      'الدفع',
  nav_cards:    'البطاقات',
  nav_more:     'المزيد',

  // ── Login ─────────────────────────────────────────────────────
  login_title:       'مرحباً بعودتك',
  login_subtitle:    'تسجيل الدخول للوصول إلى حسابك',
  login_mpin_label:  'أدخل رمز MPIN',
  login_btn_login:   'تسجيل الدخول',
  login_forgot:      'نسيت رمز MPIN؟',
  login_biometric:   'المس للمصادقة',
  login_bio_sub:     'استخدم بصمتك المسجلة',
  login_face_id:     'Face ID',
  login_mpin:        'MPIN',
  login_password:    'كلمة المرور',
  login_quick_access:'الوصول السريع',
  login_open_acct:   'فتح حساب',
  login_atm_branch:  'الصراف والفروع',
  login_support:     'الدعم',
  login_track_app:   'تتبع طلبي',
  login_no_login:    'لا يلزم تسجيل الدخول',
  login_secure:      'خدمات مصرفية آمنة 256-bit',
  login_switch:      'تبديل',
  login_last_login:  'آخر تسجيل دخول:',

  // ── Home ──────────────────────────────────────────────────────
  home_greeting_morning:   'صباح الخير',
  home_greeting_afternoon: 'مساء الخير',
  home_greeting_evening:   'مساء النور',
  home_rel_value:          'قيمة العلاقة',
  home_net_worth:          'صافي الثروة',
  home_available_bal:      'الرصيد المتاح',
  home_cash_pos:           'وضع النقد',
  home_investments:        'الاستثمارات',
  home_loan_exposure:      'التعرض للقروض',
  home_spending_overview:  'نظرة عامة على الإنفاق',
  home_analytics:          'التحليلات',
  home_income:             'الدخل',
  home_expenses:           'المصروفات',
  home_quick_actions:      'الإجراءات السريعة',
  home_view_all:           'عرض الكل',
  home_recent_tx:          'آخر المعاملات',
  home_see_all:            'عرض الكل',
  home_mask_balance:       'إخفاء الرصيد',
  home_qa_transfer:        'تحويل',
  home_qa_pay_bill:        'دفع الفواتير',
  home_qa_recharge:        'شحن',
  home_qa_qr:              'دفع QR',
  home_qa_history:         'السجل',
  home_qa_invest:          'الاستثمار',
  home_qa_loans:           'القروض',
  home_qa_more:            'المزيد',

  // ── Accounts ──────────────────────────────────────────────────
  acc_title:           'حساباتي',
  acc_total_balance:   'إجمالي الرصيد',
  acc_active_accounts: '{n} حسابات نشطة',
  acc_tab_current:     'الجاري والتوفير',
  acc_tab_deposits:    'الودائع',
  acc_tab_loans:       'القروض',
  acc_available:       'الرصيد المتاح',
  acc_open_new:        'فتح حساب',
  acc_detail_title:    'تفاصيل الحساب',
  acc_tab_overview:    'نظرة عامة',
  acc_tab_transactions:'المعاملات',
  acc_tab_analytics:   'التحليلات',
  acc_action_transfer: 'تحويل',
  acc_action_statement:'كشف الحساب',
  acc_action_iban:     'مشاركة IBAN',
  acc_action_more:     'المزيد',
  acc_recent_activity: 'النشاط الأخير',
  acc_monthly_cashflow:'التدفق النقدي الشهري',
  acc_credited:        'مُضاف',
  acc_debited:         'مُخصوم',
  acc_profit_ytd:      'الربح منذ بداية العام',
  acc_spending_breakdown: 'تفصيل الإنفاق',

  // ── Pay ───────────────────────────────────────────────────────
  pay_title:             'المدفوعات',
  pay_transfer:          'تحويل',
  pay_more_payments:     'مدفوعات أخرى',
  pay_own_account:       'حساباتي',
  pay_within_bank:       'داخل البنك',
  pay_domestic:          'محلي',
  pay_international:     'دولي',
  pay_gcc_rtgs:          'GCC RTGS',
  pay_afaq:              'آفاق',
  pay_qr:                'دفع QR',
  pay_adhoc:             'تحويل مباشر',
  pay_beneficiaries:     'المستفيدون',
  pay_templates:         'القوالب',
  pay_scheduled:         'المدفوعات المجدولة',
  pay_standing:          'التعليمات الدائمة',
  pay_bulk:              'المدفوعات الجماعية',
  pay_bills:             'دفع الفواتير',
  pay_step_recipient:    'المستفيد',
  pay_step_amount:       'المبلغ',
  pay_step_review:       'المراجعة',
  pay_step_verify:       'التحقق',
  pay_select_recipient:  'اختر المستفيد',
  pay_enter_amount:      'أدخل المبلغ',
  pay_review_transfer:   'مراجعة التحويل',
  pay_transfer_type:     'نوع التحويل',
  pay_within_aman:       'داخل بنك أمان',
  pay_other_banks:       'بنوك أخرى',
  pay_swift:             'دولي',
  pay_purpose:           'الغرض',
  pay_note:              'ملاحظة (اختياري)',
  pay_schedule:          'جدولة',
  pay_schedule_date:     'تاريخ التحويل',
  pay_amount_placeholder:'0.00',
  pay_quick_amounts:     'مبالغ سريعة',
  pay_from_account:      'من حساب',
  pay_to_beneficiary:    'إلى',
  pay_transfer_amount:   'المبلغ',
  pay_btn_continue:      'متابعة',
  pay_btn_confirm:       'تأكيد وإرسال OTP',
  pay_btn_verify:        'تحقق وحوّل',
  pay_btn_resend:        'إعادة إرسال OTP',
  pay_otp_title:         'أدخل رمز OTP',
  pay_otp_subtitle:      'تم إرسال رمز لمرة واحدة إلى جوالك المسجل',
  pay_success_title:     'تم التحويل بنجاح!',
  pay_success_ref:       'رقم المرجع',
  pay_success_amount:    'المبلغ المحوّل',
  pay_success_date:      'التاريخ والوقت',
  pay_success_btn_home:  'العودة إلى الرئيسية',
  pay_success_btn_share: 'مشاركة الإيصال',
  pay_err_invalid_amount:'أدخل مبلغاً صحيحاً',
  pay_err_select_ben:    'يرجى اختيار مستفيد',
  pay_err_failed:        'فشل التحويل. يرجى المحاولة مجدداً.',
  pay_err_otp_invalid:   'رمز OTP غير صحيح. حاول مجدداً.',
  pay_err_otp_failed:    'فشل التحقق من OTP.',
  pay_countdown:         'إعادة الإرسال خلال {time}',

  // ── Cards ─────────────────────────────────────────────────────
  cards_title:        'بطاقاتي',
  cards_add:          'إضافة بطاقة',
  cards_tab_debit:    'بطاقة خصم',
  cards_tab_credit:   'بطاقة ائتمان',
  cards_tab_virtual:  'بطاقة افتراضية',
  cards_spend_limit:  'حد الإنفاق',
  cards_block:        'إيقاف البطاقة',
  cards_set_limit:    'تحديد الحد',
  cards_change_pin:   'تغيير الرقم السري',
  cards_view_details: 'عرض التفاصيل',
  cards_hotlist:      'القائمة السوداء',
  cards_manage:       'إدارة',
  cards_reissue:      'إعادة إصدار',
  cards_freeze:       'تجميد',
  cards_unfreeze:     'رفع التجميد',
  cards_month_spend:  'الإنفاق الشهري',
  cards_available:    'المتاح',
  cards_credit_limit: 'حد الائتمان',
  cards_expires:      'تنتهي',

  // ── More ──────────────────────────────────────────────────────
  more_title:         'المزيد',
  more_profile:       'ملفي الشخصي',
  more_settings:      'الإعدادات',
  more_notifications: 'الإشعارات',
  more_analytics:     'تحليلات الإنفاق',
  more_locate:        'ابحث عن صراف أو فرع',
  more_contact:       'تواصل مع الدعم',
  more_language:      'اللغة',
  more_sign_out:      'تسجيل الخروج',
  more_security:      'الأمان والخصوصية',
  more_limits:        'حدود المعاملات',
  more_feedback:      'التغذية الراجعة',

  // ── Interrupt Handler ─────────────────────────────────────────
  interrupt_otp_title:      'كلمة المرور لمرة واحدة',
  interrupt_otp_subtitle:   'أدخل رمز OTP المرسل إلى جوالك المسجل',
  interrupt_otp_btn:        'تحقق من OTP',
  interrupt_otp_resend:     'إعادة إرسال OTP',
  interrupt_approval_title: 'تتطلب موافقة',
  interrupt_approval_sub:   'تتطلب هذه المعاملة موافقة من مُفوِّض',
  interrupt_approval_btn:   'إرسال للموافقة',
  interrupt_cancel:         'إلغاء',
  interrupt_countdown:      'ينتهي OTP خلال {time}',

  // ── Common ────────────────────────────────────────────────────
  btn_cancel:    'إلغاء',
  btn_close:     'إغلاق',
  btn_save:      'حفظ',
  btn_confirm:   'تأكيد',
  btn_retry:     'إعادة المحاولة',
  btn_back:      'رجوع',
  btn_done:      'تم',
  btn_next:      'التالي',
  btn_submit:    'إرسال',
  lbl_from:      'من',
  lbl_to:        'إلى',
  lbl_amount:    'المبلغ',
  lbl_date:      'التاريخ',
  lbl_status:    'الحالة',
  lbl_ref:       'رقم المرجع',
  lbl_active:    'نشط',
  lbl_inactive:  'غير نشط',
  lbl_today:     'اليوم',
  lbl_yesterday: 'أمس',
  status_success:'ناجح',
  status_pending:'قيد الانتظار',
  status_failed: 'فشل',
  err_generic:   'حدث خطأ ما. يرجى المحاولة مجدداً.',
  err_no_network:'لا يوجد اتصال بالإنترنت.',
  currency_lyd:  'د.ل',
  currency_aed:  'درهم',
  currency_usd:  'دولار'
});
