define({
  root: {
    more_title: 'More',
    more_profile: 'My Profile',
    more_settings: 'Settings',
    more_notifications: 'Notifications',
    more_analytics: 'Spend Analytics',
    more_locate: 'Find ATM / Branch',
    more_contact: 'Contact Support',
    more_language: 'Language',
    more_sign_out: 'Sign Out',
    more_security: 'Security & Privacy',
    more_limits: 'Transaction Limits',
    more_feedback: 'Feedback',
    more_section_account: 'Account',
    more_section_profile: 'Profile & Settings',
    more_section_services: 'Services',
    more_section_apps: 'Applications',
    more_section_support: 'Support',
    more_primary_acct: 'Primary Account',
    more_open_acct: 'Open New Account',
    more_profile_kyc: 'Profile & KYC',
    more_theme: 'Theme & Appearance',
    more_track_app: 'Track Application',
    more_live_chat: 'Live Chat',
    more_call_center: 'Call Center',
    more_investments: 'Investments',
    more_forex: 'Forex',
    more_statements: 'Statements',
    more_signout_confirm: 'Sign Out?',
    more_signout_sub: 'You will need to log back in to access your account.',
    more_rm_label: 'Your Relationship Manager',
    more_stat_accounts: 'Accounts',
    more_stat_cards: 'Cards',
    more_stat_verified: 'Verified',
    more_notif_unread: 'Unread',
    more_notif_caught_up: 'All caught up',
    more_notif_empty: 'No unread notifications right now.',
    more_notif_channels: 'Notification Channels',
    more_push_notif: 'Push Notifications',
    more_push_sub: 'In-app alerts',
    more_email_notif: 'Email Notifications',
    more_alert_cats: 'Alert Categories',
    more_alert_security: 'Security Alerts',
    more_alert_tx: 'Transaction Alerts',
    more_alert_reminders: 'Payment Reminders',
    more_alert_offers: 'Offers & Promotions',
    more_sec_auth: 'Access & Authentication',
    more_sec_face_id: 'Face ID / Biometrics',
    more_sec_face_sub: 'Login with fingerprint or face',
    more_sec_mpin_lock: 'MPIN Lock',
    more_sec_mpin_sub: '6-digit PIN required on launch',
    more_sec_2fa: '2-Factor Auth (OTP)',
    more_sec_2fa_sub: 'SMS OTP for transactions',
    more_sec_creds: 'Credentials',
    more_sec_change_mpin: 'Change MPIN',
    more_sec_mpin_row_sub: 'Update your 6-digit PIN',
    more_sec_change_pwd: 'Change Password',
    more_sec_pwd_row_sub: 'Update your login password',
    more_sec_sessions: 'Active Sessions',
    more_sec_end_all: 'End all others',
    more_sec_end: 'End',
    more_sec_trusted: 'Trusted Devices',
    more_sec_remove: 'Remove',
    more_sec_no_trusted: 'No trusted devices',
    more_this_device: 'THIS DEVICE',
    more_sec_update_mpin: 'Update MPIN',
    more_sec_mpin_hint: 'Enter your 6-digit PIN',
    more_sec_cur_mpin: 'Current MPIN',
    more_sec_new_mpin: 'New MPIN',
    more_sec_confirm_mpin: 'Confirm New MPIN',
    more_sec_update_pwd: 'Update Password',
    more_sec_pwd_hint: 'Min 8 chars · Uppercase · Number · Symbol',
    more_sec_cur_pwd: 'Current Password',
    more_sec_new_pwd: 'New Password',
    more_sec_confirm_pwd: 'Confirm New Password',
    more_kyc_verified: 'KYC Verified',
    more_personal_info: 'Personal Information',
    more_kyc_locked: 'KYC Locked',
    more_contact_details: 'Contact Details',
    more_mobile: 'Mobile',
    more_email_lbl: 'Email',
    more_address: 'Address',
    more_edit_contact: 'Edit Contact Details',
    more_save_changes: 'Save Changes',
    more_stmt_select_acct: 'Select Account',
    more_stmt_period: 'Statement Period',
    more_stmt_preparing: 'Preparing…',
    more_theme_preview: 'Preview',
    more_theme_appearance: 'Appearance',
    more_theme_accent: 'Accent Color',
    more_theme_text_size: 'Text Size',
    more_theme_light: 'Light',
    more_theme_dark: 'Dark',
    more_theme_system: 'System',
    more_theme_normal: 'Normal',
    more_theme_large: 'Large',
    more_theme_selected: 'Selected:',
    more_theme_apply: 'Apply Changes',
    more_inv_total: 'Total Portfolio Value',
    more_inv_return: '1Y Return',
    more_inv_active_funds: 'Active Funds',
    more_inv_alloc: 'Asset Allocation',
    more_inv_funds: 'My Funds',
    more_inv_more: 'Invest More',
    more_inv_withdraw: 'Withdraw',
    more_forex_title: 'Forex & Rates',
    more_forex_live: 'Live rates',
    more_forex_currency: 'Currency',
    more_forex_buy: 'Buy',
    more_forex_sell: 'Sell',
    more_track_contact: 'Contact Assigned Officer',
    more_primary_desc: 'Your primary account is used for direct debits, salary credits, and default transfers.',
    more_set_primary: 'Set as Primary',
    more_already_primary: 'Already Primary',
    acc_dl_statement: 'Download Statement',
    acc_filter_all: 'All',
    acc_format: 'Format',
    acc_sms_alerts: 'SMS Alerts',
    btn_cancel: 'Cancel',
    home_qa_loans: 'Loans',
    notif_mark_all_read: 'Mark all read',
  },
  ar: true
});
