define({
  acc_title: 'حساباتي',
  acc_total_balance: 'إجمالي الرصيد',
  acc_active_accounts: '{n} حسابات نشطة',
  acc_tab_current: 'الجاري والتوفير',
  acc_tab_deposits: 'الودائع',
  acc_tab_loans: 'القروض',
  acc_available: 'الرصيد المتاح',
  acc_open_new: 'فتح حساب',
  acc_detail_title: 'تفاصيل الحساب',
  acc_tab_overview: 'نظرة عامة',
  acc_tab_transactions: 'المعاملات',
  acc_tab_analytics: 'التحليلات',
  acc_action_transfer: 'تحويل',
  acc_action_statement: 'كشف الحساب',
  acc_action_iban: 'مشاركة IBAN',
  acc_action_more: 'المزيد',
  acc_recent_activity: 'النشاط الأخير',
  acc_monthly_cashflow: 'التدفق النقدي الشهري',
  acc_credited: 'مُضاف',
  acc_debited: 'مُخصوم',
  acc_profit_ytd: 'الربح منذ بداية العام',
  acc_spending_breakdown: 'تفصيل الإنفاق',
  acc_subtitle: 'إدارة وعرض حساباتك',
  acc_open_account: 'فتح حساب',
  acc_open_deposit: 'فتح وديعة',
  acc_apply_loan: 'طلب قرض',
  acc_no_of_accounts: 'عدد الحسابات',
  acc_today_change: 'تغيير اليوم',
  acc_total_deposited: 'إجمالي الودائع',
  acc_active_deposits: 'الودائع النشطة',
  acc_interest_ytd: 'الفائدة منذ بداية العام',
  acc_total_outstanding: 'إجمالي المستحق',
  acc_active_loans: 'القروض النشطة',
  acc_next_emi: 'القسط القادم',
  acc_know_spending: 'تعرف على إنفاقك',
  acc_offers_for_you: 'عروض لك',
  acc_available_label: 'المتاح',
  acc_account_type: 'نوع الحساب',
  acc_account_number: 'رقم الحساب',
  acc_iban: 'رقم IBAN',
  acc_currency: 'العملة',
  acc_profit_rate: 'معدل الربح',
  acc_branch: 'الفرع',
  acc_opened: 'تاريخ الفتح',
  acc_this_month_lc: 'هذا الشهر',
  acc_view_full_an: 'عرض التحليلات الكاملة ←',
  acc_upcoming_pmts: 'المدفوعات القادمة',
  acc_search_tx: 'البحث في المعاملات…',
  acc_filter_all: 'الكل',
  acc_filter_credit: 'إيداع',
  acc_filter_debit: 'سحب',
  acc_filter_transfers: 'التحويلات',
  acc_filter_bills: 'الفواتير',
  acc_an_month: 'الشهر',
  acc_an_year: 'السنة',
  acc_net_savings: 'صافي المدخرات',
  acc_top_merchants: 'أعلى التجار إنفاقاً',
  acc_share_details: 'مشاركة تفاصيل الحساب',
  acc_copy_iban: 'نسخ IBAN',
  acc_dl_statement: 'تنزيل كشف الحساب',
  acc_stmt_last_3m: 'آخر 3 أشهر',
  acc_stmt_last_6m: 'آخر 6 أشهر',
  acc_custom_range: 'نطاق مخصص',
  acc_format: 'الصيغة',
  acc_more_options: 'المزيد من الخيارات',
  acc_set_primary: 'تعيين كرئيسي',
  acc_account_alerts: 'تنبيهات الحساب',
  acc_generate_qr: 'إنشاء رمز QR',
  acc_cheque_book: 'دفتر الشيكات',
  acc_cheque_status: 'حالة الشيك',
  acc_stop_cheque: 'إيقاف الشيك',
  acc_e_statement: 'كشف إلكتروني',
  acc_nickname: 'الاسم المستعار',
  acc_block_account: 'حجب الحساب',
  acc_bal_alert: 'تنبيه الرصيد',
  acc_credit_alert: 'تنبيه الإيداع',
  acc_debit_alert: 'تنبيه السحب',
  acc_cheque_alert: 'تنبيه الشيك',
  acc_save_prefs: 'حفظ التفضيلات',
  acc_req_chq_book: 'طلب دفتر شيكات',
  acc_leaves: 'عدد الأوراق',
  acc_delivery: 'طريقة التسليم',
  acc_branch_pickup: 'الاستلام من الفرع',
  acc_courier: 'التسليم عبر البريد',
  acc_confirm_req: 'تأكيد الطلب',
  acc_chq_status_inq: 'استعلام حالة الشيك',
  acc_from_chq_no: 'من رقم الشيك',
  acc_to_chq_no: 'إلى رقم الشيك',
  acc_results: 'النتائج',
  acc_chq_no_col: 'رقم الشيك',
  acc_stop_unblock: 'إيقاف / رفع الحجب عن الشيك',
  acc_unblock: 'رفع الحجب',
  acc_chq_number: 'رقم الشيك',
  acc_stop_reason: 'السبب',
  acc_e_stat_sub: 'الاشتراك في الكشف الإلكتروني',
  acc_email_statement: 'كشف البريد الإلكتروني',
  acc_sms_alerts: 'تنبيهات SMS',
  acc_email_address: 'البريد الإلكتروني',
  acc_frequency: 'التكرار',
  acc_nickname_title: 'اسم مستعار للحساب',
  acc_nickname_label: 'الاسم المستعار',
  acc_block_reason_lbl: 'سبب الحجب',
  acc_block_lost: 'بطاقة مفقودة / مسروقة مرتبطة',
  acc_block_suspicious: 'نشاط مشبوه',
  acc_block_temp: 'تعليق مؤقت',
  home_income: 'الدخل',
  home_expenses: 'المصروفات',
  home_see_all: 'عرض الكل',
  home_view_all: 'عرض الكل',
  an_monthly_trend: 'الاتجاه الشهري',
  an_quarter: 'ربع السنة',
  an_spending_by_cat: 'الإنفاق حسب الفئة',
  an_this_month: 'هذا الشهر',
  btn_cancel: 'إلغاء',
  btn_close: 'إغلاق',
  btn_download: 'تنزيل',
  btn_load_more: 'تحميل المزيد',
  btn_save: 'حفظ',
  btn_share: 'مشاركة',
  btn_confirm_block: 'تأكيد الحجب',
  btn_submit_req: 'إرسال الطلب',
  btn_subscribe: 'اشتراك',
  lbl_active: 'نشط',
  lbl_bill: 'فاتورة',
  lbl_credit: 'دائن',
  lbl_debit: 'مدين',
  lbl_today: 'اليوم',
  lbl_yesterday: 'أمس',
  acc_view_details: 'عرض التفاصيل',
});
