define({
  root: {
    acc_title: 'My Accounts',
    acc_total_balance: 'Total Balance',
    acc_active_accounts: '{n} Active Accounts',
    acc_tab_current: 'Current & Savings',
    acc_tab_deposits: 'Deposits',
    acc_tab_loans: 'Loans',
    acc_available: 'Available Balance',
    acc_open_new: 'Open Account',
    acc_detail_title: 'Account Details',
    acc_tab_overview: 'Overview',
    acc_tab_transactions: 'Transactions',
    acc_tab_analytics: 'Analytics',
    acc_action_transfer: 'Transfer',
    acc_action_statement: 'Statement',
    acc_action_iban: 'Share IBAN',
    acc_action_more: 'More',
    acc_recent_activity: 'Recent Activity',
    acc_monthly_cashflow: 'Monthly Cash Flow',
    acc_credited: 'Credited',
    acc_debited: 'Debited',
    acc_profit_ytd: 'Profit YTD',
    acc_spending_breakdown: 'Spending Breakdown',
    acc_subtitle: 'Manage and view your accounts',
    acc_open_account: 'Open Account',
    acc_open_deposit: 'Open Deposit',
    acc_apply_loan: 'Apply Loan',
    acc_no_of_accounts: 'No. of Accounts',
    acc_today_change: 'Today\'s Change',
    acc_total_deposited: 'Total Deposited',
    acc_active_deposits: 'Active Deposits',
    acc_interest_ytd: 'Interest YTD',
    acc_total_outstanding: 'Total Outstanding',
    acc_active_loans: 'Active Loans',
    acc_next_emi: 'Next EMI',
    acc_know_spending: 'Know your spending',
    acc_offers_for_you: 'Offers for You',
    acc_available_label: 'Available',
    acc_account_type: 'Account Type',
    acc_account_number: 'Account Number',
    acc_iban: 'IBAN',
    acc_currency: 'Currency',
    acc_profit_rate: 'Profit Rate',
    acc_branch: 'Branch',
    acc_opened: 'Opened',
    acc_this_month_lc: 'This month',
    acc_view_full_an: 'View Full Analytics →',
    acc_upcoming_pmts: 'Upcoming Payments',
    acc_search_tx: 'Search transactions…',
    acc_filter_all: 'All',
    acc_filter_credit: 'Credit',
    acc_filter_debit: 'Debit',
    acc_filter_transfers: 'Transfers',
    acc_filter_bills: 'Bills',
    acc_an_month: 'Month',
    acc_an_year: 'Year',
    acc_net_savings: 'Net Savings',
    acc_top_merchants: 'Top Merchants',
    acc_share_details: 'Share Account Details',
    acc_copy_iban: 'Copy IBAN',
    acc_dl_statement: 'Download Statement',
    acc_stmt_last_3m: 'Last 3 Months',
    acc_stmt_last_6m: 'Last 6 Months',
    acc_custom_range: 'Custom Range',
    acc_format: 'Format',
    acc_more_options: 'More Options',
    acc_set_primary: 'Set as Primary',
    acc_account_alerts: 'Account Alerts',
    acc_generate_qr: 'Generate QR',
    acc_cheque_book: 'Cheque Book',
    acc_cheque_status: 'Cheque Status',
    acc_stop_cheque: 'Stop Cheque',
    acc_e_statement: 'E-statement',
    acc_nickname: 'Nickname',
    acc_block_account: 'Block Account',
    acc_bal_alert: 'Balance Alert',
    acc_credit_alert: 'Credit Alert',
    acc_debit_alert: 'Debit Alert',
    acc_cheque_alert: 'Cheque Alert',
    acc_save_prefs: 'Save Preferences',
    acc_req_chq_book: 'Request Cheque Book',
    acc_leaves: 'Number of Leaves',
    acc_delivery: 'Delivery Method',
    acc_branch_pickup: 'Branch Pickup',
    acc_courier: 'Courier Delivery',
    acc_confirm_req: 'Confirm Request',
    acc_chq_status_inq: 'Cheque Status Inquiry',
    acc_from_chq_no: 'From Cheque No.',
    acc_to_chq_no: 'To Cheque No.',
    acc_results: 'Results',
    acc_chq_no_col: 'Cheque No.',
    acc_stop_unblock: 'Stop / Unblock Cheque',
    acc_unblock: 'Unblock',
    acc_chq_number: 'Cheque Number',
    acc_stop_reason: 'Reason',
    acc_e_stat_sub: 'Subscribe for E-statement',
    acc_email_statement: 'Email Statement',
    acc_sms_alerts: 'SMS Alerts',
    acc_email_address: 'Email Address',
    acc_frequency: 'Frequency',
    acc_nickname_title: 'Account Nickname',
    acc_nickname_label: 'Nickname',
    acc_block_reason_lbl: 'Reason for blocking',
    acc_block_lost: 'Lost / Stolen card linked',
    acc_block_suspicious: 'Suspicious activity',
    acc_block_temp: 'Temporary hold',
    home_income: 'Income',
    home_expenses: 'Expenses',
    home_see_all: 'See All',
    home_view_all: 'View All',
    an_monthly_trend: 'Monthly Trend',
    an_quarter: 'Quarter',
    an_spending_by_cat: 'Spending by Category',
    an_this_month: 'This Month',
    btn_cancel: 'Cancel',
    btn_close: 'Close',
    btn_download: 'Download',
    btn_load_more: 'Load More',
    btn_save: 'Save',
    btn_share: 'Share',
    btn_confirm_block: 'Confirm Block',
    btn_submit_req: 'Submit Request',
    btn_subscribe: 'Subscribe',
    lbl_active: 'Active',
    lbl_bill: 'Bill',
    lbl_credit: 'Credit',
    lbl_debit: 'Debit',
    lbl_today: 'Today',
    lbl_yesterday: 'Yesterday',
    acc_view_details: 'View Details',
  },
  ar: true
});
