define({
  root: {
    pay_title: 'Payments',
    pay_transfer: 'Transfer',
    pay_more_payments: 'More Payments',
    pay_own_account: 'Own Account',
    pay_within_bank: 'Within Bank',
    pay_domestic: 'Domestic',
    pay_international: 'International',
    pay_gcc_rtgs: 'GCC RTGS',
    pay_afaq: 'AFAQ',
    pay_qr: 'QR Pay',
    pay_adhoc: 'Adhoc',
    pay_beneficiaries: 'Beneficiaries',
    pay_templates: 'Templates',
    pay_scheduled: 'Scheduled Payments',
    pay_standing: 'Standing Instructions',
    pay_bulk: 'Bulk Payments',
    pay_bills: 'Pay Bills',
    pay_step_recipient: 'Recipient',
    pay_step_amount: 'Amount',
    pay_step_review: 'Review',
    pay_step_verify: 'Verify',
    pay_select_recipient: 'Select Recipient',
    pay_enter_amount: 'Enter Amount',
    pay_review_transfer: 'Review Transfer',
    pay_transfer_type: 'Transfer Type',
    pay_other_banks: 'Other Banks',
    pay_swift: 'International',
    pay_purpose: 'Purpose',
    pay_note: 'Note (optional)',
    pay_schedule: 'Schedule',
    pay_schedule_date: 'Transfer Date',
    pay_amount_placeholder: '0.00',
    pay_quick_amounts: 'Quick Amounts',
    pay_from_account: 'From Account',
    pay_to_beneficiary: 'To',
    pay_transfer_amount: 'Amount',
    pay_btn_continue: 'Continue',
    pay_btn_confirm: 'Confirm & Send OTP',
    pay_btn_verify: 'Verify & Transfer',
    pay_btn_resend: 'Resend OTP',
    pay_otp_title: 'Enter OTP',
    pay_otp_subtitle: 'A one-time password was sent to your registered mobile',
    pay_success_title: 'Transfer Successful!',
    pay_success_ref: 'Reference No.',
    pay_success_amount: 'Amount Transferred',
    pay_success_date: 'Date & Time',
    pay_success_btn_home: 'Back to Home',
    pay_success_btn_share: 'Share Receipt',
    pay_err_invalid_amount: 'Enter a valid amount',
    pay_err_select_ben: 'Please select a beneficiary',
    pay_err_failed: 'Transfer failed. Please try again.',
    pay_err_otp_invalid: 'Invalid OTP. Try again.',
    pay_err_otp_failed: 'OTP verification failed.',
    pay_countdown: 'Resend in {time}',
    pay_fund_transfer: 'Fund Transfer',
    pay_tracker: 'Payment Tracker',
    pay_share_qr: 'Share QR',
    pay_scan_pay: 'Scan & Pay',
    pay_add_ben: '+ Add',
    pay_new_scheduled: '+ New Scheduled Payment',
    pay_recent_ben: 'Recent Beneficiaries',
    pay_no_ben: 'No beneficiaries yet',
    pay_transfer_to: 'Transfer To',
    pay_you_sending: 'You are sending',
    pay_service_charges: 'Service Charges',
    pay_total_debit: 'Total Debit',
    pay_btn_review: 'Review Transfer →',
    pay_sending: 'Sending…',
    pay_verify_title: 'Verify Your Transfer',
    pay_otp_sent: 'A 6-digit OTP has been sent to',
    pay_resend_in: 'Resend OTP in',
    pay_money_way: 'Your money is on its way',
    pay_amount_sent: 'Amount Sent',
    pay_completed: 'Completed',
    pay_btn_receipt: 'Receipt',
    pay_btn_track: 'Track',
    pay_back_payments: 'Back to Payments',
    pay_schedule_later: 'Schedule for later',
    pay_account_no: 'Account No.',
    pay_within_bank_sub: 'Same bank transfers',
    pay_other_banks_sub: 'Domestic local transfer',
    pay_intl: 'International',
    pay_intl_sub: 'SWIFT / IBAN',
    lbl_from: 'From',
    lbl_to: 'To',
    lbl_status: 'Status',
  },
  ar: true
});
