define({
  home_greeting_morning: 'صباح الخير',
  home_greeting_afternoon: 'مساء الخير',
  home_greeting_evening: 'مساء النور',
  home_rel_value: 'قيمة العلاقة',
  home_net_worth: 'صافي الثروة',
  home_available_bal: 'الرصيد المتاح',
  home_cash_pos: 'وضع النقد',
  home_investments: 'الاستثمارات',
  home_loan_exposure: 'التعرض للقروض',
  home_spending_overview: 'نظرة عامة على الإنفاق',
  home_analytics: 'التحليلات',
  home_income: 'الدخل',
  home_expenses: 'المصروفات',
  home_quick_actions: 'الإجراءات السريعة',
  home_view_all: 'عرض الكل',
  home_recent_tx: 'آخر المعاملات',
  home_see_all: 'عرض الكل',
  home_mask_balance: 'إخفاء الرصيد',
  home_qa_transfer: 'تحويل',
  home_qa_pay_bill: 'دفع الفواتير',
  home_qa_recharge: 'شحن',
  home_qa_qr: 'دفع QR',
  home_qa_history: 'السجل',
  home_qa_invest: 'الاستثمار',
  home_qa_loans: 'القروض',
  home_qa_more: 'المزيد',
  home_no_tx: 'لا توجد معاملات حديثة',
  home_savings: 'المدخرات',
  home_analytics_link: '‹ التحليلات',
  home_net_worth: 'صافي الثروة',
  home_rel_value: 'قيمة العلاقة',
  notif_mark_all_read: 'تحديد الكل كمقروء',
  more_notifications: 'الإشعارات',
  an_insights: 'التحليلات والرؤى',
  an_this_month: 'هذا الشهر',
  an_quarter: 'ربع السنة',
  an_this_year: 'هذا العام',
  an_cash_flow: 'التدفق النقدي',
  an_spending_by_cat: 'الإنفاق حسب الفئة',
  an_monthly_trend: 'الاتجاه الشهري',
  an_top_expenses: 'أعلى المصروفات',
  an_net: 'الصافي',
  an_total: 'المجموع',
});
