define({
  splash_tagline: 'اختبر الخدمات المصرفية الرقمية من الجيل القادم',
  splash_securing: 'جاري تأمين جلستك...',
  login_title: 'مرحباً بعودتك',
  login_subtitle: 'تسجيل الدخول للوصول إلى حسابك',
  login_mpin_label: 'أدخل رمز MPIN',
  login_mpin_hint: 'رقم التعريف الشخصي المكون من 6 أرقام',
  login_btn_login: 'تسجيل الدخول',
  login_btn_loading: 'جاري تسجيل الدخول...',
  login_signin_label: 'تسجيل الدخول',
  login_forgot: 'نسيت رمز MPIN؟',
  login_forgot_pwd: 'نسيت كلمة المرور؟',
  login_biometric: 'المس للمصادقة',
  login_bio_sub: 'استخدم بصمتك المسجلة',
  login_face_label: 'انظر للمصادقة',
  login_face_sub: 'استخدم Face ID لتسجيل الدخول',
  login_face_id: 'Face ID',
  login_fingerprint: 'بصمة الإصبع',
  login_mpin: 'MPIN',
  login_password: 'كلمة المرور',
  login_username: 'اسم المستخدم',
  login_username_ph: 'أدخل اسم المستخدم',
  login_password_ph: 'أدخل كلمة المرور',
  login_credentials_sub: 'أدخل بيانات الاعتماد',
  login_quick_access: 'الوصول السريع',
  login_open_acct: 'فتح حساب',
  login_atm_branch: 'الصراف والفروع',
  login_support: 'الدعم',
  login_track_app: 'تتبع طلبي',
  login_no_login: 'لا يلزم تسجيل الدخول',
  login_secure: 'خدمات مصرفية آمنة 256-bit',
  login_switch: 'تبديل',
  login_last_login: 'آخر تسجيل دخول:',
});
