define({
  root: {
    splash_tagline: 'Experience Next-Gen Digital Banking',
    splash_securing: 'Securing your session...',
    login_title: 'Welcome Back',
    login_subtitle: 'Sign in to access your account',
    login_mpin_label: 'Enter MPIN',
    login_mpin_hint: 'Your 6-digit secure PIN',
    login_btn_login: 'Sign In',
    login_btn_loading: 'Signing in…',
    login_signin_label: 'Sign In',
    login_forgot: 'Forgot MPIN?',
    login_forgot_pwd: 'Forgot Password?',
    login_biometric: 'Touch to Authenticate',
    login_bio_sub: 'Use your registered fingerprint',
    login_face_label: 'Look to Authenticate',
    login_face_sub: 'Use Face ID to sign in',
    login_face_id: 'Face ID',
    login_fingerprint: 'Fingerprint',
    login_mpin: 'MPIN',
    login_password: 'Password',
    login_username: 'Username',
    login_username_ph: 'Enter your username',
    login_password_ph: 'Enter your password',
    login_credentials_sub: 'Enter your credentials',
    login_quick_access: 'Quick Access',
    login_open_acct: 'Open Account',
    login_atm_branch: 'ATM & Branch',
    login_support: 'Support',
    login_track_app: 'Track My Application',
    login_no_login: 'No login needed',
    login_secure: '256-bit Secure Banking',
    login_switch: 'Switch',
    login_last_login: 'Last login:',
  },
  ar: true
});
