define({
  root: {
    home_greeting_morning: 'Good morning',
    home_greeting_afternoon: 'Good afternoon',
    home_greeting_evening: 'Good evening',
    home_rel_value: 'Relationship Value',
    home_net_worth: 'Net Worth',
    home_available_bal: 'Available Bal',
    home_cash_pos: 'Cash Position',
    home_investments: 'Investments',
    home_loan_exposure: 'Loan Exposure',
    home_spending_overview: 'Spending Overview',
    home_analytics: 'Analytics',
    home_income: 'Income',
    home_expenses: 'Expenses',
    home_quick_actions: 'Quick Actions',
    home_view_all: 'View All',
    home_recent_tx: 'Recent Transactions',
    home_see_all: 'See All',
    home_mask_balance: 'Hide balance',
    home_qa_transfer: 'Transfer',
    home_qa_pay_bill: 'Pay Bills',
    home_qa_recharge: 'Recharge',
    home_qa_qr: 'QR Pay',
    home_qa_history: 'History',
    home_qa_invest: 'Invest',
    home_qa_loans: 'Loans',
    home_qa_more: 'More',
    home_no_tx: 'No recent transactions',
    home_savings: 'Savings',
    home_analytics_link: 'Analytics ›',
    home_net_worth: 'Net Worth',
    home_rel_value: 'Relationship Value',
    notif_mark_all_read: 'Mark all read',
    more_notifications: 'Notifications',
    an_insights: 'Analytics & Insights',
    an_this_month: 'This Month',
    an_quarter: 'Quarter',
    an_this_year: 'This Year',
    an_cash_flow: 'Cash Flow',
    an_spending_by_cat: 'Spending by Category',
    an_monthly_trend: 'Monthly Trend',
    an_top_expenses: 'Top Expenses',
    an_net: 'Net',
    an_total: 'Total',
  },
  ar: true
});
