define({
  root: {
    appName: 'Aman Bank',

    // ── Navigation ────────────────────────────────────────────────
    nav_home:     'Home',
    nav_accounts: 'Accounts',
    nav_pay:      'Pay',
    nav_cards:    'Cards',
    nav_more:     'More',

    // ── Login ─────────────────────────────────────────────────────
    login_title:       'Welcome Back',
    login_subtitle:    'Sign in to access your account',
    login_mpin_label:  'Enter MPIN',
    login_btn_login:   'Login',
    login_forgot:      'Forgot MPIN?',
    login_biometric:   'Touch to Authenticate',
    login_bio_sub:     'Use your registered fingerprint',
    login_face_id:     'Face ID',
    login_mpin:        'MPIN',
    login_password:    'Password',
    login_quick_access:'Quick Access',
    login_open_acct:   'Open Account',
    login_atm_branch:  'ATM & Branch',
    login_support:     'Support',
    login_track_app:   'Track My Application',
    login_no_login:    'No login needed',
    login_secure:      '256-bit Secure Banking',
    login_switch:      'Switch',
    login_last_login:  'Last login:',

    // ── Home ──────────────────────────────────────────────────────
    home_greeting_morning:   'Good morning',
    home_greeting_afternoon: 'Good afternoon',
    home_greeting_evening:   'Good evening',
    home_rel_value:          'Relationship Value',
    home_net_worth:          'Net Worth',
    home_available_bal:      'Available Bal',
    home_cash_pos:           'Cash Position',
    home_investments:        'Investments',
    home_loan_exposure:      'Loan Exposure',
    home_spending_overview:  'Spending Overview',
    home_analytics:          'Analytics',
    home_income:             'Income',
    home_expenses:           'Expenses',
    home_quick_actions:      'Quick Actions',
    home_view_all:           'View All',
    home_recent_tx:          'Recent Transactions',
    home_see_all:            'See All',
    home_mask_balance:       'Hide balance',
    home_qa_transfer:        'Transfer',
    home_qa_pay_bill:        'Pay Bills',
    home_qa_recharge:        'Recharge',
    home_qa_qr:              'QR Pay',
    home_qa_history:         'History',
    home_qa_invest:          'Invest',
    home_qa_loans:           'Loans',
    home_qa_more:            'More',

    // ── Accounts ──────────────────────────────────────────────────
    acc_title:           'My Accounts',
    acc_total_balance:   'Total Balance',
    acc_active_accounts: '{n} Active Accounts',
    acc_tab_current:     'Current & Savings',
    acc_tab_deposits:    'Deposits',
    acc_tab_loans:       'Loans',
    acc_available:       'Available Balance',
    acc_open_new:        'Open Account',
    acc_detail_title:    'Account Details',
    acc_tab_overview:    'Overview',
    acc_tab_transactions:'Transactions',
    acc_tab_analytics:   'Analytics',
    acc_action_transfer: 'Transfer',
    acc_action_statement:'Statement',
    acc_action_iban:     'Share IBAN',
    acc_action_more:     'More',
    acc_recent_activity: 'Recent Activity',
    acc_monthly_cashflow:'Monthly Cash Flow',
    acc_credited:        'Credited',
    acc_debited:         'Debited',
    acc_profit_ytd:      'Profit YTD',
    acc_spending_breakdown: 'Spending Breakdown',

    // ── Pay ───────────────────────────────────────────────────────
    pay_title:             'Payments',
    pay_transfer:          'Transfer',
    pay_more_payments:     'More Payments',
    pay_own_account:       'Own Account',
    pay_within_bank:       'Within Bank',
    pay_domestic:          'Domestic',
    pay_international:     'International',
    pay_gcc_rtgs:          'GCC RTGS',
    pay_afaq:              'AFAQ',
    pay_qr:                'QR Pay',
    pay_adhoc:             'Adhoc',
    pay_beneficiaries:     'Beneficiaries',
    pay_templates:         'Templates',
    pay_scheduled:         'Scheduled Payments',
    pay_standing:          'Standing Instructions',
    pay_bulk:              'Bulk Payments',
    pay_bills:             'Pay Bills',
    pay_step_recipient:    'Recipient',
    pay_step_amount:       'Amount',
    pay_step_review:       'Review',
    pay_step_verify:       'Verify',
    pay_select_recipient:  'Select Recipient',
    pay_enter_amount:      'Enter Amount',
    pay_review_transfer:   'Review Transfer',
    pay_transfer_type:     'Transfer Type',
    pay_within_aman:       'Within Aman',
    pay_other_banks:       'Other Banks',
    pay_swift:             'International',
    pay_purpose:           'Purpose',
    pay_note:              'Note (optional)',
    pay_schedule:          'Schedule',
    pay_schedule_date:     'Transfer Date',
    pay_amount_placeholder:'0.00',
    pay_quick_amounts:     'Quick Amounts',
    pay_from_account:      'From Account',
    pay_to_beneficiary:    'To',
    pay_transfer_amount:   'Amount',
    pay_btn_continue:      'Continue',
    pay_btn_confirm:       'Confirm & Send OTP',
    pay_btn_verify:        'Verify & Transfer',
    pay_btn_resend:        'Resend OTP',
    pay_otp_title:         'Enter OTP',
    pay_otp_subtitle:      'A one-time password was sent to your registered mobile',
    pay_success_title:     'Transfer Successful!',
    pay_success_ref:       'Reference No.',
    pay_success_amount:    'Amount Transferred',
    pay_success_date:      'Date & Time',
    pay_success_btn_home:  'Back to Home',
    pay_success_btn_share: 'Share Receipt',
    pay_err_invalid_amount:'Enter a valid amount',
    pay_err_select_ben:    'Please select a beneficiary',
    pay_err_failed:        'Transfer failed. Please try again.',
    pay_err_otp_invalid:   'Invalid OTP. Try again.',
    pay_err_otp_failed:    'OTP verification failed.',
    pay_countdown:         'Resend in {time}',

    // ── Cards ─────────────────────────────────────────────────────
    cards_title:         'My Cards',
    cards_add:           'Add Card',
    cards_tab_debit:     'Debit',
    cards_tab_credit:    'Credit',
    cards_tab_virtual:   'Virtual',
    cards_spend_limit:   'Spend Limit',
    cards_block:         'Block Card',
    cards_set_limit:     'Set Limit',
    cards_change_pin:    'Change PIN',
    cards_view_details:  'View Details',
    cards_hotlist:       'Hotlist',
    cards_manage:        'Manage',
    cards_reissue:       'Reissue',
    cards_freeze:        'Freeze',
    cards_unfreeze:      'Unfreeze',
    cards_month_spend:   'Month Spend',
    cards_available:     'Available',
    cards_credit_limit:  'Credit Limit',
    cards_expires:       'Expires',

    // ── More ──────────────────────────────────────────────────────
    more_title:          'More',
    more_profile:        'My Profile',
    more_settings:       'Settings',
    more_notifications:  'Notifications',
    more_analytics:      'Spend Analytics',
    more_locate:         'Find ATM / Branch',
    more_contact:        'Contact Support',
    more_language:       'Language',
    more_sign_out:       'Sign Out',
    more_security:       'Security & Privacy',
    more_limits:         'Transaction Limits',
    more_feedback:       'Feedback',

    // ── Interrupt Handler ─────────────────────────────────────────
    interrupt_otp_title:    'One-Time Password',
    interrupt_otp_subtitle: 'Enter the OTP sent to your registered mobile number',
    interrupt_otp_btn:      'Verify OTP',
    interrupt_otp_resend:   'Resend OTP',
    interrupt_approval_title:  'Approval Required',
    interrupt_approval_sub:    'This transaction requires approval from an authoriser',
    interrupt_approval_btn:    'Submit for Approval',
    interrupt_cancel:          'Cancel',
    interrupt_countdown:       'OTP expires in {time}',

    // ── Common ────────────────────────────────────────────────────
    btn_cancel:    'Cancel',
    btn_close:     'Close',
    btn_save:      'Save',
    btn_confirm:   'Confirm',
    btn_retry:     'Retry',
    btn_back:      'Back',
    btn_done:      'Done',
    btn_next:      'Next',
    btn_submit:    'Submit',
    lbl_from:      'From',
    lbl_to:        'To',
    lbl_amount:    'Amount',
    lbl_date:      'Date',
    lbl_status:    'Status',
    lbl_ref:       'Reference No.',
    lbl_active:    'Active',
    lbl_inactive:  'Inactive',
    lbl_today:     'Today',
    lbl_yesterday: 'Yesterday',
    status_success:'Success',
    status_pending:'Pending',
    status_failed: 'Failed',
    err_generic:   'Something went wrong. Please try again.',
    err_no_network:'No network connection. Please check your internet.',
    currency_lyd:  'LYD',
    currency_aed:  'AED',
    currency_usd:  'USD'
  },
  ar: true
});
