define({
  root: {
    appName: 'OBDX Bank',

    // ── Navigation ────────────────────────────────────────────────
    nav_home:     'Home',
    nav_accounts: 'Accounts',
    nav_pay:      'Pay',
    nav_cards:    'Cards',
    nav_more:     'More',

    // ── Splash ────────────────────────────────────────────────────
    splash_tagline:  'Experience Next-Gen Digital Banking',
    splash_securing: 'Securing your session...',

    // ── Login ─────────────────────────────────────────────────────
    login_title:          'Welcome Back',
    login_subtitle:       'Sign in to access your account',
    login_mpin_label:     'Enter MPIN',
    login_mpin_hint:      'Your 6-digit secure PIN',
    login_btn_login:      'Sign In',
    login_btn_loading:    'Signing in…',
    login_signin_label:   'Sign In',
    login_forgot:         'Forgot MPIN?',
    login_forgot_pwd:     'Forgot Password?',
    login_biometric:      'Touch to Authenticate',
    login_bio_sub:        'Use your registered fingerprint',
    login_face_label:     'Look to Authenticate',
    login_face_sub:       'Use Face ID to sign in',
    login_face_id:        'Face ID',
    login_fingerprint:    'Fingerprint',
    login_mpin:           'MPIN',
    login_password:       'Password',
    login_username:       'Username',
    login_username_ph:    'Enter your username',
    login_password_ph:    'Enter your password',
    login_credentials_sub:'Enter your credentials',
    login_quick_access:   'Quick Access',
    login_open_acct:      'Open Account',
    login_atm_branch:     'ATM & Branch',
    login_support:        'Support',
    login_track_app:      'Track My Application',
    login_no_login:       'No login needed',
    login_secure:         '256-bit Secure Banking',
    login_switch:         'Switch',
    login_last_login:     'Last login:',

    // ── Home ──────────────────────────────────────────────────────
    home_greeting_morning:   'Good morning',
    home_greeting_afternoon: 'Good afternoon',
    home_greeting_evening:   'Good evening',
    home_rel_value:          'Relationship Value',
    home_net_worth:          'Net Worth',
    home_available_bal:      'Available Bal',
    home_cash_pos:           'Cash Position',
    home_investments:        'Investments',
    home_loan_exposure:      'Loan Exposure',
    home_spending_overview:  'Spending Overview',
    home_analytics:          'Analytics',
    home_income:             'Income',
    home_expenses:           'Expenses',
    home_quick_actions:      'Quick Actions',
    home_view_all:           'View All',
    home_recent_tx:          'Recent Transactions',
    home_see_all:            'See All',
    home_mask_balance:       'Hide balance',
    home_qa_transfer:        'Transfer',
    home_qa_pay_bill:        'Pay Bills',
    home_qa_recharge:        'Recharge',
    home_qa_qr:              'QR Pay',
    home_qa_history:         'History',
    home_qa_invest:          'Invest',
    home_qa_loans:           'Loans',
    home_qa_more:            'More',
    home_no_tx:              'No recent transactions',
    home_savings:            'Savings',
    home_analytics_link:     'Analytics ›',
    notif_mark_all_read:     'Mark all read',
    an_insights:             'Analytics & Insights',
    an_this_month:           'This Month',
    an_quarter:              'Quarter',
    an_this_year:            'This Year',
    an_cash_flow:            'Cash Flow',
    an_spending_by_cat:      'Spending by Category',
    an_monthly_trend:        'Monthly Trend',
    an_top_expenses:         'Top Expenses',
    an_net:                  'Net',
    an_total:                'Total',

    // ── Accounts ──────────────────────────────────────────────────
    acc_title:           'My Accounts',
    acc_total_balance:   'Total Balance',
    acc_active_accounts: '{n} Active Accounts',
    acc_tab_current:     'Current & Savings',
    acc_tab_deposits:    'Deposits',
    acc_tab_loans:       'Loans',
    acc_available:       'Available Balance',
    acc_open_new:        'Open Account',
    acc_detail_title:    'Account Details',
    acc_tab_overview:    'Overview',
    acc_tab_transactions:'Transactions',
    acc_tab_analytics:   'Analytics',
    acc_action_transfer: 'Transfer',
    acc_action_statement:'Statement',
    acc_action_iban:     'Share IBAN',
    acc_action_more:     'More',
    acc_recent_activity: 'Recent Activity',
    acc_monthly_cashflow:'Monthly Cash Flow',
    acc_credited:        'Credited',
    acc_debited:         'Debited',
    acc_profit_ytd:      'Profit YTD',
    acc_spending_breakdown: 'Spending Breakdown',

    // ── Accounts (additions) ──────────────────────────────────────────────
    acc_subtitle:        'Manage and view your accounts',
    acc_open_account:    'Open Account',
    acc_open_deposit:    'Open Deposit',
    acc_apply_loan:      'Apply Loan',
    acc_no_of_accounts:  'No. of Accounts',
    acc_today_change:    "Today's Change",
    acc_total_deposited: 'Total Deposited',
    acc_active_deposits: 'Active Deposits',
    acc_interest_ytd:    'Interest YTD',
    acc_total_outstanding:'Total Outstanding',
    acc_active_loans:    'Active Loans',
    acc_next_emi:        'Next EMI',
    acc_know_spending:   'Know your spending',
    acc_offers_for_you:  'Offers for You',
    acc_available_label: 'Available',
    acc_account_type:    'Account Type',
    acc_account_number:  'Account Number',
    acc_iban:            'IBAN',
    acc_currency:        'Currency',
    acc_profit_rate:     'Profit Rate',
    acc_branch:          'Branch',
    acc_opened:          'Opened',
    acc_this_month_lc:   'This month',
    acc_view_full_an:    'View Full Analytics →',
    acc_upcoming_pmts:   'Upcoming Payments',
    btn_download:        'Download',
    acc_search_tx:       'Search transactions…',
    acc_filter_all:      'All',
    acc_filter_credit:   'Credit',
    acc_filter_debit:    'Debit',
    acc_filter_transfers:'Transfers',
    acc_filter_bills:    'Bills',
    btn_load_more:       'Load More',
    acc_an_month:        'Month',
    acc_an_year:         'Year',
    acc_net_savings:     'Net Savings',
    acc_top_merchants:   'Top Merchants',
    acc_share_details:   'Share Account Details',
    acc_copy_iban:       'Copy IBAN',
    btn_share:           'Share',
    acc_dl_statement:    'Download Statement',
    acc_stmt_last_3m:    'Last 3 Months',
    acc_stmt_last_6m:    'Last 6 Months',
    acc_custom_range:    'Custom Range',
    acc_format:          'Format',
    acc_more_options:    'More Options',
    acc_set_primary:     'Set as Primary',
    acc_account_alerts:  'Account Alerts',
    acc_generate_qr:     'Generate QR',
    acc_cheque_book:     'Cheque Book',
    acc_cheque_status:   'Cheque Status',
    acc_stop_cheque:     'Stop Cheque',
    acc_e_statement:     'E-statement',
    acc_nickname:        'Nickname',
    acc_block_account:   'Block Account',
    acc_bal_alert:       'Balance Alert',
    acc_credit_alert:    'Credit Alert',
    acc_debit_alert:     'Debit Alert',
    acc_cheque_alert:    'Cheque Alert',
    acc_save_prefs:      'Save Preferences',
    acc_req_chq_book:    'Request Cheque Book',
    acc_leaves:          'Number of Leaves',
    acc_delivery:        'Delivery Method',
    acc_branch_pickup:   'Branch Pickup',
    acc_courier:         'Courier Delivery',
    acc_confirm_req:     'Confirm Request',
    acc_chq_status_inq:  'Cheque Status Inquiry',
    acc_from_chq_no:     'From Cheque No.',
    acc_to_chq_no:       'To Cheque No.',
    acc_results:         'Results',
    acc_chq_no_col:      'Cheque No.',
    acc_stop_unblock:    'Stop / Unblock Cheque',
    acc_unblock:         'Unblock',
    acc_chq_number:      'Cheque Number',
    acc_stop_reason:     'Reason',
    btn_submit_req:      'Submit Request',
    acc_e_stat_sub:      'Subscribe for E-statement',
    acc_email_statement: 'Email Statement',
    acc_sms_alerts:      'SMS Alerts',
    acc_email_address:   'Email Address',
    acc_frequency:       'Frequency',
    btn_subscribe:       'Subscribe',
    acc_nickname_title:  'Account Nickname',
    acc_nickname_label:  'Nickname',
    acc_block_reason_lbl:'Reason for blocking',
    acc_block_lost:      'Lost / Stolen card linked',
    acc_block_suspicious:'Suspicious activity',
    acc_block_temp:      'Temporary hold',
    btn_confirm_block:   'Confirm Block',

    // ── Pay ───────────────────────────────────────────────────────
    pay_title:             'Payments',
    pay_transfer:          'Transfer',
    pay_more_payments:     'More Payments',
    pay_own_account:       'Own Account',
    pay_within_bank:       'Within Bank',
    pay_domestic:          'Domestic',
    pay_international:     'International',
    pay_gcc_rtgs:          'GCC RTGS',
    pay_afaq:              'AFAQ',
    pay_qr:                'QR Pay',
    pay_adhoc:             'Adhoc',
    pay_beneficiaries:     'Beneficiaries',
    pay_templates:         'Templates',
    pay_scheduled:         'Scheduled Payments',
    pay_standing:          'Standing Instructions',
    pay_bulk:              'Bulk Payments',
    pay_bills:             'Pay Bills',
    pay_step_recipient:    'Recipient',
    pay_step_amount:       'Amount',
    pay_step_review:       'Review',
    pay_step_verify:       'Verify',
    pay_select_recipient:  'Select Recipient',
    pay_enter_amount:      'Enter Amount',
    pay_review_transfer:   'Review Transfer',
    pay_transfer_type:     'Transfer Type',

    pay_other_banks:       'Other Banks',
    pay_swift:             'International',
    pay_purpose:           'Purpose',
    pay_note:              'Note (optional)',
    pay_schedule:          'Schedule',
    pay_schedule_date:     'Transfer Date',
    pay_amount_placeholder:'0.00',
    pay_quick_amounts:     'Quick Amounts',
    pay_from_account:      'From Account',
    pay_to_beneficiary:    'To',
    pay_transfer_amount:   'Amount',
    pay_btn_continue:      'Continue',
    pay_btn_confirm:       'Confirm & Send OTP',
    pay_btn_verify:        'Verify & Transfer',
    pay_btn_resend:        'Resend OTP',
    pay_otp_title:         'Enter OTP',
    pay_otp_subtitle:      'A one-time password was sent to your registered mobile',
    pay_success_title:     'Transfer Successful!',
    pay_success_ref:       'Reference No.',
    pay_success_amount:    'Amount Transferred',
    pay_success_date:      'Date & Time',
    pay_success_btn_home:  'Back to Home',
    pay_success_btn_share: 'Share Receipt',
    pay_err_invalid_amount:'Enter a valid amount',
    pay_err_select_ben:    'Please select a beneficiary',
    pay_err_failed:        'Transfer failed. Please try again.',
    pay_err_otp_invalid:   'Invalid OTP. Try again.',
    pay_err_otp_failed:    'OTP verification failed.',
    pay_countdown:         'Resend in {time}',
    pay_fund_transfer:    'Fund Transfer',
    pay_tracker:          'Payment Tracker',
    pay_share_qr:         'Share QR',
    pay_scan_pay:         'Scan & Pay',
    pay_add_ben:          '+ Add',
    pay_new_scheduled:    '+ New Scheduled Payment',
    pay_recent_ben:       'Recent Beneficiaries',
    pay_no_ben:           'No beneficiaries yet',
    pay_transfer_to:      'Transfer To',
    pay_you_sending:      'You are sending',
    pay_service_charges:  'Service Charges',
    pay_total_debit:      'Total Debit',
    pay_btn_review:       'Review Transfer →',
    pay_sending:          'Sending…',
    pay_verify_title:     'Verify Your Transfer',
    pay_otp_sent:         'A 6-digit OTP has been sent to',
    pay_resend_in:        'Resend OTP in',
    pay_money_way:        'Your money is on its way',
    pay_amount_sent:      'Amount Sent',
    pay_completed:        'Completed',
    pay_btn_receipt:      'Receipt',
    pay_btn_track:        'Track',
    pay_back_payments:    'Back to Payments',
    pay_schedule_later:   'Schedule for later',
    pay_account_no:       'Account No.',
    pay_within_bank:      'Within Bank',
    pay_within_bank_sub:  'Same bank transfers',
    pay_other_banks:      'Other Banks',
    pay_other_banks_sub:  'Domestic local transfer',
    pay_intl:             'International',
    pay_intl_sub:         'SWIFT / IBAN',

    // ── Cards ─────────────────────────────────────────────────────
    cards_title:         'My Cards',
    cards_add:           'Add Card',
    cards_tab_debit:     'Debit',
    cards_tab_credit:    'Credit',
    cards_tab_virtual:   'Virtual',
    cards_spend_limit:   'Spend Limit',
    cards_block:         'Block Card',
    cards_set_limit:     'Set Limit',
    cards_change_pin:    'Change PIN',
    cards_view_details:  'View Details',
    cards_hotlist:       'Hotlist',
    cards_manage:        'Manage',
    cards_reissue:       'Reissue',
    cards_freeze:        'Freeze',
    cards_unfreeze:      'Unfreeze',
    cards_month_spend:   'Month Spend',
    cards_available:     'Available',
    cards_credit_limit:  'Credit Limit',
    cards_expires:       'Expires',
    cards_subtitle:      'Tap a card to view details',
    cards_new_card:      'New Card',
    cards_set_limits:    'Set Limits',
    cards_spending_limits:'Spending Limits',
    cards_disputes:      'Disputes',
    cards_e_statement:   'e-Statement',
    cards_info:          'Card Info',
    cards_replace:       'Replace Card',
    cards_daily:         'Daily',
    cards_monthly:       'Monthly',
    cards_daily_limit:   'Daily Limit',
    cards_monthly_limit: 'Monthly Limit',
    cards_save_limits:   'Save Limits',
    cards_no_tx:         'No transactions yet',
    cards_auth_title:    'Verify Your Identity',
    cards_auth_sub:      'Choose how to authenticate to view card details',
    cards_auth_bio:      'Biometric',
    cards_auth_bio_sub:  'Use Face ID or Fingerprint',
    cards_auth_mpin_sub: 'Enter your 6-digit MPIN',
    cards_auth_mpin_hint:'Enter your 6-digit Mobile PIN',
    cards_auth_otp:      'OTP via SMS',
    cards_view_front:    'View Front',
    cards_view_back:     'View Back',
    cards_block_reason:  'Select a reason for blocking this card. This action can be reversed.',
    cards_confirm_block: 'Block Card',
    cards_request:       'Request New Card',
    cards_debit_card:    'Debit Card',
    cards_debit_sub:     'Linked to your current account',
    cards_credit_card:   'Credit Card',
    cards_credit_sub:    'Subject to credit approval',
    cards_virtual_card:  'Virtual Card',
    cards_virtual_sub:   'Instant, for online purchases',

    // ── More ──────────────────────────────────────────────────────
    more_title:          'More',
    more_profile:        'My Profile',
    more_settings:       'Settings',
    more_notifications:  'Notifications',
    more_analytics:      'Spend Analytics',
    more_locate:         'Find ATM / Branch',
    more_contact:        'Contact Support',
    more_language:       'Language',
    more_sign_out:       'Sign Out',
    more_security:       'Security & Privacy',
    more_limits:         'Transaction Limits',
    more_feedback:       'Feedback',
    // More — menu sections & tiles
    more_section_account:  'Account',
    more_section_profile:  'Profile & Settings',
    more_section_services: 'Services',
    more_section_apps:     'Applications',
    more_section_support:  'Support',
    more_primary_acct:     'Primary Account',
    more_open_acct:        'Open New Account',
    more_profile_kyc:      'Profile & KYC',
    more_theme:            'Theme & Appearance',
    more_track_app:        'Track Application',
    more_live_chat:        'Live Chat',
    more_call_center:      'Call Center',
    more_investments:      'Investments',
    more_forex:            'Forex',
    more_statements:       'Statements',
    more_signout_confirm:  'Sign Out?',
    more_signout_sub:      'You will need to log back in to access your account.',
    // More — hero stats
    more_rm_label:         'Your Relationship Manager',
    more_stat_accounts:    'Accounts',
    more_stat_cards:       'Cards',
    more_stat_verified:    'Verified',
    // More — notifications
    more_notif_unread:     'Unread',
    more_notif_caught_up:  'All caught up',
    more_notif_empty:      'No unread notifications right now.',
    more_notif_channels:   'Notification Channels',
    more_push_notif:       'Push Notifications',
    more_push_sub:         'In-app alerts',
    more_email_notif:      'Email Notifications',
    more_alert_cats:       'Alert Categories',
    more_alert_security:   'Security Alerts',
    more_alert_tx:         'Transaction Alerts',
    more_alert_reminders:  'Payment Reminders',
    more_alert_offers:     'Offers & Promotions',
    // More — security
    more_sec_auth:         'Access & Authentication',
    more_sec_face_id:      'Face ID / Biometrics',
    more_sec_face_sub:     'Login with fingerprint or face',
    more_sec_mpin_lock:    'MPIN Lock',
    more_sec_mpin_sub:     '6-digit PIN required on launch',
    more_sec_2fa:          '2-Factor Auth (OTP)',
    more_sec_2fa_sub:      'SMS OTP for transactions',
    more_sec_creds:        'Credentials',
    more_sec_change_mpin:  'Change MPIN',
    more_sec_mpin_row_sub: 'Update your 6-digit PIN',
    more_sec_change_pwd:   'Change Password',
    more_sec_pwd_row_sub:  'Update your login password',
    more_sec_sessions:     'Active Sessions',
    more_sec_end_all:      'End all others',
    more_sec_end:          'End',
    more_sec_trusted:      'Trusted Devices',
    more_sec_remove:       'Remove',
    more_sec_no_trusted:   'No trusted devices',
    more_this_device:      'THIS DEVICE',
    more_sec_update_mpin:  'Update MPIN',
    more_sec_mpin_hint:    'Enter your 6-digit PIN',
    more_sec_cur_mpin:     'Current MPIN',
    more_sec_new_mpin:     'New MPIN',
    more_sec_confirm_mpin: 'Confirm New MPIN',
    more_sec_update_pwd:   'Update Password',
    more_sec_pwd_hint:     'Min 8 chars · Uppercase · Number · Symbol',
    more_sec_cur_pwd:      'Current Password',
    more_sec_new_pwd:      'New Password',
    more_sec_confirm_pwd:  'Confirm New Password',
    // More — profile
    more_kyc_verified:     'KYC Verified',
    more_personal_info:    'Personal Information',
    more_kyc_locked:       'KYC Locked',
    more_contact_details:  'Contact Details',
    more_mobile:           'Mobile',
    more_email_lbl:        'Email',
    more_address:          'Address',
    more_edit_contact:     'Edit Contact Details',
    more_save_changes:     'Save Changes',
    // More — statements
    more_stmt_select_acct: 'Select Account',
    more_stmt_period:      'Statement Period',
    more_stmt_preparing:   'Preparing…',
    // More — theme
    more_theme_preview:    'Preview',
    more_theme_appearance: 'Appearance',
    more_theme_accent:     'Accent Color',
    more_theme_text_size:  'Text Size',
    more_theme_light:      'Light',
    more_theme_dark:       'Dark',
    more_theme_system:     'System',
    more_theme_normal:     'Normal',
    more_theme_large:      'Large',
    more_theme_selected:   'Selected:',
    more_theme_apply:      'Apply Changes',
    // More — investments
    more_inv_total:        'Total Portfolio Value',
    more_inv_return:       '1Y Return',
    more_inv_active_funds: 'Active Funds',
    more_inv_alloc:        'Asset Allocation',
    more_inv_funds:        'My Funds',
    more_inv_more:         'Invest More',
    more_inv_withdraw:     'Withdraw',
    // More — forex
    more_forex_title:      'Forex & Rates',
    more_forex_live:       'Live rates',
    more_forex_currency:   'Currency',
    more_forex_buy:        'Buy',
    more_forex_sell:       'Sell',
    // More — tracking & primary account
    more_track_contact:    'Contact Assigned Officer',
    more_primary_desc:     'Your primary account is used for direct debits, salary credits, and default transfers.',
    more_set_primary:      'Set as Primary',
    more_already_primary:  'Already Primary',

    // ── Interrupt Handler ─────────────────────────────────────────
    interrupt_otp_title:    'One-Time Password',
    interrupt_otp_subtitle: 'Enter the OTP sent to your registered mobile number',
    interrupt_otp_btn:      'Verify OTP',
    interrupt_otp_resend:   'Resend OTP',
    interrupt_approval_title:  'Approval Required',
    interrupt_approval_sub:    'This transaction requires approval from an authoriser',
    interrupt_approval_btn:    'Submit for Approval',
    interrupt_cancel:          'Cancel',
    interrupt_countdown:       'OTP expires in {time}',

    // ── Common ────────────────────────────────────────────────────
    btn_cancel:    'Cancel',
    btn_close:     'Close',
    btn_save:      'Save',
    btn_confirm:   'Confirm',
    btn_retry:     'Retry',
    btn_back:      'Back',
    btn_done:      'Done',
    btn_next:      'Next',
    btn_submit:    'Submit',
    lbl_from:      'From',
    lbl_to:        'To',
    lbl_amount:    'Amount',
    lbl_date:      'Date',
    lbl_status:    'Status',
    lbl_ref:       'Reference No.',
    lbl_active:    'Active',
    lbl_inactive:  'Inactive',
    lbl_today:     'Today',
    lbl_yesterday: 'Yesterday',
    lbl_credit:    'Credit',
    lbl_debit:     'Debit',
    lbl_bill:      'Bill',
    status_success:'Success',
    status_pending:'Pending',
    status_failed: 'Failed',
    err_generic:   'Something went wrong. Please try again.',
    err_no_network:'No network connection. Please check your internet.',
    currency_lyd:  'LYD',
    currency_aed:  'AED',
    currency_usd:  'USD'
  },
  ar: true
});
